### ISSUE TITLE
《人人都能用英语》地址无法访问

### ISSUE THREAD

**Issue by heyuanchao** [xiaolai/bitcoin-whitepaper-chinese-translation#3]
http://zhibimo.com/books/xiaolai/everyone-can-use-english 这个地址无法访问，zhibimo.com 也无法 Ping 通

![image](https://user-images.githubusercontent.com/10580354/47639444-3c6da580-db9c-11e8-99f3-a15c9dc1fba0.png)

**Comment by x1angli** [comment]
貌似知笔墨这个网站已经不运营了

别的网站有留存，如
https://www.w3cschool.cn/use_english/
（该地址是否经原作者授权不得而知，仅供信息查阅使用）

**Comment by heyuanchao** [comment]
谢谢，放在知笔墨上的文章都看不到了，幸好之前都看过，希望老师有时间把这些文章重新发布到 lixiaolai.com 上

《把时间当朋友》
《七年就是一辈子》
《挤挤都会有的 - 写给女生的性高潮指南》
《成长 - YC创业课（CS183B）学习笔记》
《TOEFL iBT 高分作文》
